### ISSUE TITLE
Race condition in deployment

### ISSUE THREAD

**Issue by davetapley** [codeship-library/heroku-deployment#16]
Context:
I just switched from Codeship Classic to Docker based builds, and our deploy step doesn't work because there is no `.git` present in the container.

That led me to look at this repo, via:
https://codeship.com/documentation/docker-integration/heroku/

---

Looking at [this part](https://github.com/codeship-library/heroku-deployment/blob/3eb5f75006498d569907ed2cf9c3badb8f046059/scripts/codeship_heroku_deploy#L27) of your sample deploy script I see you use [tar and platform API](https://devcenter.heroku.com/articles/build-and-release-using-the-api) approach for deployment.

Unfortunately I believe this introduces an issue:

Consider the possibility that a build for _a commit older than that which is currently deployed_ completes it tests, and [starts its deployment step](https://codeship.com/documentation/docker-integration/heroku/#deploy-steps). This could happen for a several reasons:
1. An early build was intentionally or accidentally restarted.
2. Two commits were pushed in rapid succession, and timing unpredictability resulted in the later commit's test steps completing prior to the former commit's test steps.

Now:
- When using _git based builds_, the subsequent attempt to push a commit which is a _parent of the most recently pushed commit_, results in a `pushed branch tip is behind its remote` error. However:
- When using the _tar-and-platform-API_ approach suggested here, I believe the deployment would take place regardless.

In the former case the build remains on the most recent code, however:
In the latter case the newer commit would be effectively reverted from the deployment.

**Comment by mohanzhang** [comment]
@dukedave Did you ever find a solution to this issue?

**Comment by davetapley** [comment]
@mohanzhang yes, we stopped using Codeship's Docker deployment :expressionless:

**Comment by ethangj** [comment]
@mohanzhang I believe you found a solution by rolling some aggressive parallelization checking, correct?
